version: '4.12'

services:

  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/static
      - files_volume:/code/files
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/code/static
      - files_volume:/code/files
    ports:
      - 80:80
    depends_on:
      - web

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data_prod:/data
    ports:
      - 6379:6379
  
  celery:
    build: .
    command: celery -A config worker -l info --pool=solo
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis

volumes:
  postgres_data_prod:
  static_volume:
  files_volume:
  redis_data_prod: